In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import random
import math as m
import sys
import os 
import csv

In [3]:
movie_ratings = np.loadtxt("/Users/Fairy/Desktop/hw8/hw8_ratings_fa18.txt")
z_i=np.loadtxt("/Users/Fairy/Desktop/hw8/hw8_probZ_init.txt")
r_given_z=np.loadtxt("/Users/Fairy/Desktop/hw8/hw8_probRgivenZ_init.txt")

location=os.getcwd()

location+="\\Desktop\\HW8\\hw8_movieTitles_fa18.txt"

movies = pd.DataFrame.from_csv(location, sep = '\t', header = -1)
movies.reset_index(inplace=True)
movies.columns=['movie_titles']


C:\Users\Fairy\AnacodaContainer\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: FutureWarning: from_csv is deprecated. Please use read_csv(...) instead. Note that some of the default arguments are different, so please refer to the documentation for from_csv when changing your function calls
  if __name__ == '__main__':


In [4]:
sanity=np.sum(np.array(movie_ratings) > 0, axis=0)/np.sum(np.array(movie_ratings) > -1, axis=0)

In [5]:
movies['popularity']=sanity

In [6]:
movies.sort_values('popularity',ascending=False)

movie_titles  popularity
0                                      Inception    0.973094
1                             The_Social_Network    0.936170
21                         The_Dark_Knight_Rises    0.925581
39                                  Interstellar    0.917874
3                                 Shutter_Island    0.891473
28                           Wolf_of_Wall_Street    0.881356
23                              Django_Unchained    0.868421
2                                     Black_Swan    0.863636
51                              Ready_Player_One    0.862903
33                              12_Years_a_Slave    0.860465
55                                Hidden_Figures    0.859649
61                                  Darkest_Hour    0.857143
50                        Avengers:_Infinity_War    0.852941
47                                   The_Martian    0.849057
11  Harry_Potter_and_the_Deathly_Hallows:_Part_2    0.845794
25                                Les_Miserables    0.844660
59               Three_Billboards_Outside_Ebbing    0.843750
37                                     Gone_Girl    0.836364
46                                          Room    0.836066
40                      The_Theory_of_Everything    0.832000
20                                  The_Avengers    0.831858
29                              The_Great_Gatsby    0.831325
32                                           Her    0.826531
7                                    Toy_Story_3    0.817680
5   Harry_Potter_and_the_Deathly_Hallows:_Part_1    0.811927
38                                    Ex_Machina    0.806818
14                            X-Men:_First_Class    0.805556
31                                Now_You_See_Me    0.792453
30                                        Frozen    0.791667
26                                21_Jump_Street    0.789474
..                                           ...         ...
16                                      The_Help    0.775000
56                         Manchester_by_the_Sea    0.768116
54                                    La_La_Land    0.766467
6                                     Iron_Man_2    0.764151
19               The_Perks_of_Being_a_Wallflower    0.759494
10            Captain_America:_The_First_Avenger    0.752427
42                            Mad_Max:_Fury_Road    0.744361
41                  Star_Wars:_The_Force_Awakens    0.744048
58                                       Dunkirk    0.732824
49                                  The_Revenant    0.730000
48                             The_Hateful_Eight    0.728814
43                                Jurassic_World    0.721649
45                       Avengers:_Age_of_Ultron    0.720812
8                                      Fast_Five    0.704000
24                                 Pitch_Perfect    0.696203
9                                           Thor    0.693467
22                              The_Hunger_Games    0.668317
15                                         Drive    0.666667
35                               American_Hustle    0.648649
12                                    Bridemaids    0.627119
34                                   World_War_Z    0.578431
27                                    Magic_Mike    0.553191
60                                Phantom_Thread    0.545455
57                            The_Shape_of_Water    0.511111
18                                    Prometheus    0.510000
36                                  Man_of_Steel    0.489209
53                                 Chappaquidick    0.454545
52                                 I_Feel_Pretty    0.363636
44                          Fifty_Shades_of_Grey    0.333333
4                             The_Last_Airbender    0.302632

[62 rows x 2 columns]

In [7]:
iterations=129
k=4
print(len(z_i))
r_given_z[0]
movie_ratings[1]
len(movies)

4


62

In [8]:
def probability_rj(t):
    sum=0
    for i in range(len(z_i)):
        sum+=z_i[i]*prob_rj_given_z_t(t,i)
    return sum

In [9]:
def prob_rj_given_z_t(t,i):
    prod=1
    omegat=movie_ratings[t]
    for index,value in enumerate(omegat):
        #print(omegat)
        if(value==1):
            prod*=r_given_z[index][i]
        elif(value==0):
            prod*=1-r_given_z[index][i]
    return prod  

In [10]:
def e_step_prob_z_i_given_rj_t(i,t):
    roit=0
    numerator=z_i[i]*prob_rj_given_z_t(t,i)
    #print(numerator)
    sum=0
    for i_dash in range(len(z_i)):
        sum+=z_i[i_dash]*prob_rj_given_z_t(t,i_dash)
    roit=numerator/sum
    #print("rp",roit)
    return roit

In [11]:
r_given_z

array([[0.4359949 , 0.02592623, 0.54966248, 0.43532239],
       [0.4203678 , 0.33033482, 0.20464863, 0.61927097],
       [0.29965467, 0.26682728, 0.62113383, 0.52914209],
       [0.13457995, 0.51357812, 0.18443987, 0.78533515],
       [0.85397529, 0.49423684, 0.84656149, 0.07964548],
       [0.50524609, 0.0652865 , 0.42812233, 0.09653092],
       [0.12715997, 0.59674531, 0.226012  , 0.10694568],
       [0.22030621, 0.34982629, 0.46778748, 0.20174323],
       [0.64040673, 0.48306984, 0.50523672, 0.38689265],
       [0.79363745, 0.58000418, 0.1622986 , 0.70075235],
       [0.96455108, 0.50000836, 0.88952006, 0.34161365],
       [0.56714413, 0.42754596, 0.43674726, 0.77655918],
       [0.53560417, 0.95374223, 0.54420816, 0.08209492],
       [0.3663424 , 0.8508505 , 0.40627504, 0.02720237],
       [0.24717724, 0.06714437, 0.99385201, 0.97058031],
       [0.80025835, 0.60181712, 0.76495986, 0.16922545],
       [0.29302323, 0.52406688, 0.35662428, 0.04567897],
       [0.98315345, 0.44135492,

In [13]:
z_i
type(z_i)

numpy.ndarray

In [25]:
def mstep(i,j,T):
    s=u=sum=0
    for t in range(T):
        sum+=e_step_prob_z_i_given_rj_t(i,t)
        #print(e_step_prob_z_i_given_rj_t(i,t))
        if(movie_ratings[t][j]==-1):
            s+=e_step_prob_z_i_given_rj_t(i,t)*r_given_z[j][i]
        elif(movie_ratings[t][j]==1):
            u+=e_step_prob_z_i_given_rj_t(i,t)
    #print("s",s)
    return (s+u)/sum,sum/T
                    

In [ ]:
T=len(movie_ratings)
ll=0
master={}
for t in range(T):
    ll+=np.log(probability_rj(t))
output={"iteration":0,"ll":ll/T}
master[0]=output
print(master)
for iter in range(1,iterations):
    x=np.zeros((len(movies),4))
    y=np.zeros(4)
    for i in range(4):
        for j in range(len(movies)):
            two,one=mstep(i,j,T)
            
            x[j][i]=two
            y[i]=one
    r_given_z=x
    z_i=y
    ll=0
    for t in range(T):
        ll+=np.log(probability_rj(t))
    output={"iteration":iter,"ll":ll/T}
    master[iter]=output
    print(output)

{0: {'iteration': 0, 'll': -26.678832965400435}}
{'iteration': 1, 'll': -16.094668997711192}
{'iteration': 2, 'll': -14.28779402734125}


In [30]:
z_i

array([0.60840609, 0.06442231, 0.14182412, 0.18534747])

In [14]:
z_i=np.asarray([0.60840609, 0.06442231, 0.14182412, 0.18534747])
r_given_z=

In [37]:
r_given_z=np.asarray([[1.00000000e+00, 7.82483781e-01, 9.11869770e-01, 1.00000000e+00],
       [9.21369213e-01, 1.00000000e+00, 8.88715814e-01, 1.00000000e+00],
       [8.50495676e-01, 6.81930224e-01, 8.31787842e-01, 1.00000000e+00],
       [8.91001536e-01, 7.76815983e-01, 8.40282921e-01, 9.65433696e-01],
       [2.92234574e-01, 3.61634944e-30, 5.13991687e-01, 3.26922721e-01],
       [1.00000000e+00, 3.05585875e-01, 2.86818573e-01, 7.12121192e-01],
       [9.26183699e-01, 8.15744412e-02, 9.62953461e-01, 2.18825455e-01],
       [8.76881877e-01, 7.64184422e-01, 7.58672460e-01, 6.88590932e-01],
       [8.23978414e-01, 3.00508238e-01, 7.68524576e-01, 4.25445324e-01],
       [8.51116717e-01, 2.20088192e-01, 6.07086709e-01, 2.97295583e-01],
       [8.87580300e-01, 1.05242196e-01, 9.12863480e-01, 2.53542667e-01],
       [9.87639397e-01, 3.00699450e-01, 4.15301957e-01, 8.53469982e-01],
       [6.52454053e-01, 5.59225939e-01, 6.13363202e-01, 5.73202606e-01],
       [7.59388018e-01, 7.78300852e-01, 8.77947349e-01, 8.27920871e-01],
       [9.03058543e-01, 1.03309328e-01, 7.87724284e-01, 6.71747810e-01],
       [6.98597504e-01, 6.75955233e-01, 4.10056644e-01, 7.76383528e-01],
       [8.05810550e-01, 5.71713112e-01, 7.10222198e-01, 9.99999879e-01],
       [7.24391047e-01, 6.62697670e-01, 9.99985518e-01, 8.92238009e-01],
       [5.87199627e-01, 1.50956204e-01, 2.04580112e-01, 6.25144838e-01],
       [7.92489915e-01, 3.27473959e-01, 6.36200808e-01, 1.00000000e+00],
       [9.78475948e-01, 3.37546019e-01, 1.00000000e+00, 3.52895265e-01],
       [9.54749864e-01, 6.04655363e-01, 1.00000000e+00, 8.93481331e-01],
       [8.69500087e-01, 1.58940271e-01, 3.68849841e-01, 3.78986427e-01],
       [8.89010146e-01, 5.32460652e-01, 8.95545174e-01, 1.00000000e+00],
       [7.82783647e-01, 9.56169444e-25, 8.55189657e-01, 5.45553038e-01],
       [8.88922714e-01, 5.59399641e-01, 8.09701297e-01, 9.04832157e-01],
       [7.81672720e-01, 5.73510837e-01, 7.66974372e-01, 9.37361904e-01],
       [5.60886383e-01, 2.36894182e-14, 7.37804433e-01, 7.14452984e-01],
       [9.34349652e-01, 4.32882505e-01, 9.22393293e-01, 8.76373794e-01],
       [8.62636818e-01, 6.17972040e-01, 7.74082898e-01, 8.79947584e-01],
       [8.15423003e-01, 5.52336045e-01, 8.58454739e-01, 7.63014966e-01],
       [8.95935082e-01, 1.93346682e-01, 7.81055655e-01, 6.62376826e-01],
       [8.21246550e-01, 7.52214625e-01, 8.64940203e-01, 8.62706412e-01],
       [8.20169417e-01, 9.10549536e-01, 9.02253900e-01, 9.00387883e-01],
       [6.69374465e-01, 1.56877843e-01, 2.05966850e-01, 7.55729630e-01],
       [7.16927022e-01, 6.28934431e-01, 4.44507017e-01, 5.52339246e-01],
       [6.05096453e-01, 1.39055818e-01, 3.41111830e-01, 3.22744184e-01],
       [8.01955212e-01, 6.28570421e-01, 8.95869016e-01, 9.47165942e-01],
       [8.60048282e-01, 5.03181752e-01, 7.16307549e-01, 9.24612888e-01],
       [9.60324294e-01, 6.36720227e-01, 8.83904773e-01, 9.02685428e-01],
       [8.84952392e-01, 7.97814279e-01, 7.49804022e-01, 7.38161882e-01],
       [8.74585528e-01, 4.04018686e-01, 6.49312832e-01, 5.00665533e-01],
       [8.14359572e-01, 3.63209066e-01, 6.11783305e-01, 8.09686032e-01],
       [8.19773587e-01, 3.46293694e-01, 3.94737240e-01, 7.61503523e-01],
       [3.82921315e-01, 1.52846451e-01, 3.59351052e-01, 1.87834954e-01],
       [9.22425575e-01, 1.65589794e-56, 8.33694209e-01, 1.16365155e-01],
       [8.38734327e-01, 8.29802807e-01, 9.99650783e-01, 7.43457331e-01],
       [8.32734566e-01, 6.63865172e-01, 1.00000000e+00, 8.48982936e-01],
       [6.77345164e-01, 5.06281684e-01, 9.99951105e-01, 8.41170487e-01],
       [7.36875145e-01, 3.77516138e-01, 8.10332557e-01, 8.07306493e-01],
       [9.56744062e-01, 5.44022119e-01, 8.50238580e-01, 5.52924236e-01],
       [1.00000000e+00, 4.97196113e-01, 7.59852968e-01, 7.27946246e-01],
       [4.99254964e-01, 1.18255204e-22, 9.18468878e-01, 8.27814205e-02],
       [4.27737754e-01, 3.33333333e-01, 2.69253932e-01, 9.91686261e-01],
       [8.07999987e-01, 8.10089639e-01, 5.83196766e-01, 7.36813796e-01],
       [8.31677024e-01, 8.03895788e-01, 1.00000000e+00, 8.15539037e-01],
       [8.57582438e-01, 2.00915312e-01, 8.76031242e-01, 6.86104844e-01],
       [5.19908471e-01, 5.84834382e-01, 3.65246055e-01, 5.54305320e-01],
       [7.49848542e-01, 5.66615916e-01, 5.39857963e-01, 8.43148108e-01],
       [8.31737385e-01, 5.20011423e-01, 9.99999984e-01, 9.21713048e-01],
       [6.25258274e-01, 5.15364970e-01, 5.86969411e-01, 4.92585545e-01],
       [8.36861990e-01, 1.00000000e+00, 1.00000000e+00, 7.17872428e-01]])

In [34]:
l=[0,1,2,4,8,16,32,64,128]
for i in l:
    print(master[i])

NameError: name 'master' is not defined

In [40]:
#r_given_z

array([[1.00000000e+00, 7.82483781e-01, 9.11869770e-01, 1.00000000e+00],
       [9.21369213e-01, 1.00000000e+00, 8.88715814e-01, 1.00000000e+00],
       [8.50495676e-01, 6.81930224e-01, 8.31787842e-01, 1.00000000e+00],
       [8.91001536e-01, 7.76815983e-01, 8.40282921e-01, 9.65433696e-01],
       [2.92234574e-01, 3.61634944e-30, 5.13991687e-01, 3.26922721e-01],
       [1.00000000e+00, 3.05585875e-01, 2.86818573e-01, 7.12121192e-01],
       [9.26183699e-01, 8.15744412e-02, 9.62953461e-01, 2.18825455e-01],
       [8.76881877e-01, 7.64184422e-01, 7.58672460e-01, 6.88590932e-01],
       [8.23978414e-01, 3.00508238e-01, 7.68524576e-01, 4.25445324e-01],
       [8.51116717e-01, 2.20088192e-01, 6.07086709e-01, 2.97295583e-01],
       [8.87580300e-01, 1.05242196e-01, 9.12863480e-01, 2.53542667e-01],
       [9.87639397e-01, 3.00699450e-01, 4.15301957e-01, 8.53469982e-01],
       [6.52454053e-01, 5.59225939e-01, 6.13363202e-01, 5.73202606e-01],
       [7.59388018e-01, 7.78300852e-01, 8.77947349e

In [33]:
#movie_ratings[91]

array([ 1.,  1., -1., -1., -1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,
        0.,  1., -1., -1., -1., -1., -1.,  1.,  1.,  1., -1., -1., -1.,
       -1., -1.,  1.,  0.,  1.,  1., -1.,  1., -1., -1., -1.,  0.,  0.,
        1.,  1.,  1., -1.,  1.,  0.,  1., -1.,  1., -1., -1.,  1., -1.,
       -1., -1.,  0., -1., -1., -1.,  1., -1., -1., -1.])

In [43]:
likely_movies={}
person=91
for mov in range(len(movies)):
    d=0
    if(movie_ratings[person][mov]==-1):
        for i in range(k):
            d+=e_step_prob_z_i_given_rj_t(i,person)*r_given_z[mov][i]
        likely_movies[movies['movie_titles'][mov]]={"expected_val":d,"movie":mov+1}
        likely_movies[movies['movie_titles'][mov]]=d

In [44]:
likely_movies
output = pd.DataFrame()
output = output.append(likely_movies, ignore_index=True)

In [45]:
O=output.T
O.columns=['expected_values']
O.sort_values('expected_values',ascending=False)

expected_values
Ready_Player_One                        0.999475
Shutter_Island                          0.890891
Django_Unchained                        0.889025
Les_Miserables                          0.888749
Manchester_by_the_Sea                   0.857623
Black_Swan                              0.850455
Room                                    0.839086
Darkest_Hour                            0.837219
Three_Billboards_Outside_Ebbing         0.832105
Hidden_Figures                          0.832045
Her                                     0.821342
Mad_Max:_Fury_Road                      0.813917
The_Help                                0.805602
The_Perks_of_Being_a_Wallflower         0.792148
Pitch_Perfect                           0.782942
21_Jump_Street                          0.781641
The_Revenant                            0.737036
Midnight_in_Paris                       0.724994
American_Hustle                         0.716331
Drive                                   0.697967
The_Hateful_Eight                       0.678051
World_War_Z                             0.668361
Phantom_Thread                          0.625174
Man_of_Steel                            0.604519
Prometheus                              0.586363
Magic_Mike                              0.561273
The_Shape_of_Water                      0.519570
I_Feel_Pretty                           0.500171
Chappaquidick                           0.427392
The_Last_Airbender                      0.292720